## HPA for lhc-app
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa-app
  namespace: lhc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:   Deployment
    name: {{ .Release.Name }}-app
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa-nodejs
  namespace: lhc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind:   Deployment
    name: {{ .Release.Name }}-nodejshelper
  minReplicas: 1
  maxReplicas: 3
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetCPUUtilizationPercentage: 50

---

## HPA for database
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa-db
  namespace: lhc
spec:
  {{- if and (eq .Values.kind "statefulset") (eq .Values.env "Production") }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind:   StatefulSet
    name: {{ .Release.Name }}-db
  minReplicas: 1
  maxReplicas: 10
  {{- else }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind:   Deployment
    name: {{ .Release.Name }}-db
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetCPUUtilizationPercentage: 50
  {{- end }}

{{- end -}}