apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app-install
  namespace: ingress-nginx
  labels:
    name: nginx-app-install
spec:
  ingressClassName: nginx
  rules:
  - host: pshung.2k
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-app-install-production
            port: 
              number: 8080
