apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ ingressnname |default("lhc-install-ingress",true)}}
  namespace: {{ env.namespace |default(nginx-app-install-production,true)}}
  labels:
    name: nginx-app-install
spec:
  # tls:
  #     - hosts:
  #       - pshung.tk
  #       secretName: lhc-secret-tls
  ingressClassName: nginx
  rules:
  - host: pshung.tk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-app-install-production
            port: 
              number: 8080
