#### PV ####
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    name: {{ .Release.Name }}-volume
spec:
  #storageClassName: mystorageclass
  capacity:
    storage: {{ .Values.capacity_matomo }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/matomo/"
    server: "172.31.38.220"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-db-volume
spec:
  #storageClassName: {{ .Values.stgclass }}
  capacity:
    storage: {{ .Values.capacity_db_matomo }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/database/"
    server: "172.31.38.220"

---
#### PVC ####
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    name: {{ .Release.Name }}-volume
spec:
#  storageClassName: mystorageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-db-volume
spec:
  selector:
    matchLabels: 
      name: {{ .Release.Name }}-db-volume
  #storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi