apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-db-volume
spec:
  selector:
    matchLabels: 
      name: {{ .Release.Name }}-db-volume
  #storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-volume
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-volume
  #storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nginx-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-nginx-volume
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-nginx-volume
  #storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 210Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-php-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-php-volume
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-php-volume
  storageClassName: {{ .Values.stgclass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-code-volume
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-code-volume
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-code-volume
  storageClassName: {{ .Values.stgclass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
