apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  labels:
    name: {{ .Release.Name }}
spec:
  #storageClassName: mystorageclass
  capacity:
    storage: {{ .Values.capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/volumematomo/"
