kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.31.38.220
  share: /mnt/matomo
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
#volumeBindingMode: WaitForFirstConsumer
