kind: Service
apiVersion: v1
metadata:
  {{- if eq .Values.env "Production" }}
  name:  {{ .Release.Name }}-production
  {{- else }}
  name: {{ .Release.Name }}
  {{- end }}
  namespace: nginx
spec:
  selector:
    name: {{ .Release.Name }}
    env: {{ .Values.env }}
  {{- if eq .Values.env "Production" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
  - name:  {{ .Release.Name }}
    {{- with .Values.service }}
    {{ include "nginx-app.port" . | nindent 4}}
    {{- end -}}


