apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.ns }}
data:
  nginx.conf: |
  {{- .Files.Get "config/site-nodejs.conf" | nindent 4 }}
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Values.ns }}
data:
  db-name: lhc