## In Prodction environment
{{- if eq .Values.env "prod" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-production
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-production
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-production
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-production
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-production
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-production
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-production
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}

## In QA environment    
{{- else if eq .Values.env "qa"}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-QA
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-QA
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-QA
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-QA
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-QA
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-QA
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-QA
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}

## In dev environment
{{- else if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-devolopment
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-devolopment
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-devolopment
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-devolopment
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-devolopment
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-devolopment
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-devolopment
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}
{{- end }}
