## In Prodction environment
{{- if eq .Values.env "prod" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-prod
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-prod
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-prod
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-prod
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-prod
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-prod
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-prod
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}

## In stag environment    
{{- else if eq .Values.env "stag"}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-stag
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-stag
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-stag
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-stag
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-stag
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-stag
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-stag
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}

## In dev environment
{{- else if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser-dev
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-db-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-db-dev
  type: ClusterIP
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport_db }}
    targetPort: {{ .Values.tgport_db }}
    #nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-app-dev
  ports:
  - port: {{ .Values.svcport_lhc_app }}
    targetPort: {{ .Values.tgport_lhc_app }}
    nodePort: 31080
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper-dev
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-php-resque-dev
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-dev
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: {{ .Release.Name }}-redis-dev
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}
{{- end }}
