apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.ns }}
  labels:
    name: {{ .Release.Name }}-ingress
    namespace: {{ .Values.ns }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - pshung.tk
      secretName: {{ .Values.ingress_secret }}
  rules:
  - host: pshung.tk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.ingress_svc_name }}
            port: 
              number: 8080
