#### For lhc-app-install ####
# lhc:
### For Nginx config ###
server: 
  listen: 
  hostname: 
  index: index index.php index.html;
  location:
    proxy_pass_njs: abcd
  root: /code_hung
  error_log: 
  access_log: 
php:
  fascgi_pass: php-hung:9000
  enable: true
  location: hung_php
nodejs:
  enable: true
  location: /wsnodejs111/_hung
  proxy_pass: hung_njs:3000
cobr:
  enable: true
  location: cobr_hung
  proxy_pass: cobr_hung:31130
lhc:  
  ### For Values file ###
  env:
    env:
    controller:
      kind: deployment
    namespace: lhc-hung
    replicas: 5
    capacitylhc: 700Mi
    capacity_db: 1.1Gi
    capacity_code: 1.2Gi
    capacity_nginx: 400Mi
    hpaenable: 
# listen: 800